### ISSUE TITLE
Auto-reconnect feature

### ISSUE THREAD

**Issue by madziaar** [MattDahEpic/MonstercatDownloader#2]
Can you add something like this? Since this small application is what I totally need and a feature like that would ease my pain with my internet provider...

**Comment by MattDahEpic** [comment]
I no longer have Monstercat Gold so I would be unable to test this feature should it be added. Somebody else has made a better, QT-based version of this program that I can't seem to find that may have the feature already. If you find it let me know, otherwise I sadly don't think I can add this at the moment.
